window.fillFormSetting = {
    "supportedControls":'input[name],select[name],textarea[name]',
    "rules":[
        {
            "siteRule":"/job/seeker/default/login",
            "fieldRule":"LoginForm[loginId]",
            "value":"seeker@m.mm"
        },
        {
            "siteRule":"/job/seeker/default/login",
            "fieldRule":"LoginForm[password]",
            "value":"123123"
        },
        {
            "siteRule":"/job/seeker/default/login",
            "fieldRule":"LoginForm[rememberMe]",
            "value":true
        },
        {
            "siteRule":"http://beautyfashioncity.com/inujob/site/signup_employers",
            "fieldRule":"LoginForm[email]",
            "value":"emp@m.mm"
        },
        {
            "siteRule":"http://beautyfashioncity.com/inujob/site/signup_employers",
            "fieldRule":"LoginForm[password]",
            "value":"123123"
        },
        {
            "siteRule":"http://beautyfashioncity.com/inujob/site/signup_employers",
            "fieldRule":"LoginForm[rememberMe]",
            "value":true
        },
        {
            "siteRule":"http://beautyfashioncity.com/inujob/admin/login",
            "fieldRule":"AdminLoginForm[username]",
            "value":"admin"
        },
        {
            "siteRule":"http://beautyfashioncity.com/inujob/admin/login",
            "fieldRule":"AdminLoginForm[password]",
            "value":"P@ss_500"
        },
        {
            "siteRule":"http://beautyfashioncity.com/inujob/admin/login",
            "fieldRule":"AdminLoginForm[rememberMe]",
            "value":true
        },
        {
            "siteRule":"/job/employer/default/login",
            "fieldRule":"LoginForm[loginId]",
            "value":"employer@m.mm"
        },
        {
            "siteRule":"/job/employer/default/login",
            "fieldRule":"LoginForm[password]",
            "value":"123123"
        },
        {
            "siteRule":"/job/employer/default/login",
            "fieldRule":"LoginForm[rememberMe]",
            "value":true
        },
        {
            "siteRule":"/job/employer/default/login",
            "fieldRule":"SignupForm[agreeTerm]",
            "value":true
        },
        {
            "siteRule":"/job/employer/default/login",
            "fieldRule":"SignupForm[business_no]",
            "value":"456789"
        },
        {
            "siteRule":"/job/employer/default/login",
            "fieldRule":"SignupForm[company_description]",
            "value":""
        },
        {
            "siteRule":"/job/employer/default/login",
            "fieldRule":"SignupForm[company]",
            "value":"Company Name"
        },
        {
            "siteRule":"/job/employer/default/login",
            "fieldRule":"SignupForm[contact_email]",
            "value":"user@m.mm"
        },
        {
            "siteRule":"/job/employer/default/login",
            "fieldRule":"SignupForm[contact_name]",
            "value":"Ace"
        },
        {
            "siteRule":"/job/employer/default/login",
            "fieldRule":"SignupForm[contact_phone]",
            "value":"44549631585"
        },
        {
            "siteRule":"/job/employer/default/login",
            "fieldRule":"SignupForm[email]",
            "value":"emp@m.mm"
        },
        {
            "siteRule":"/job/employer/default/login",
            "fieldRule":"SignupForm[ew_no]",
            "value":"ER12536"
        },
        {
            "siteRule":"/job/employer/default/login",
            "fieldRule":"SignupForm[password_repeat]",
            "value":"123123"
        },
        {
            "siteRule":"/job/employer/default/login",
            "fieldRule":"SignupForm[password]",
            "value":"123123"
        },
        {
            "siteRule":"/job/employer/default/login",
            "fieldRule":"SignupForm[receive_promotion_email]",
            "value":true
        },
        {
            "siteRule":"/job/employer/default/login",
            "fieldRule":"SignupForm[receive_resume_email]",
            "value":true
        },
        {
            "siteRule":"/job/employer/job/add",
            "fieldRule":"JobForm[company]",
            "value":"Amaris"
        },
        {
            "siteRule":"/job/employer/job/add",
            "fieldRule":"JobForm[description]",
            "value":"description"
        },
        {
            "siteRule":"/job/employer/job/add",
            "fieldRule":"JobForm[display_salary]",
            "value":true
        },
        {
            "siteRule":"/job/employer/job/add",
            "fieldRule":"JobForm[duration]",
            "value":"1"
        },
        {
            "siteRule":"/job/employer/job/add",
            "fieldRule":"JobForm[hide_company]",
            "value":true
        },
        {
            "siteRule":"/job/employer/job/add",
            "fieldRule":"JobForm[job_title]",
            "value":"AngularJS Developer"
        },
        {
            "siteRule":"/job/employer/job/add",
            "fieldRule":"JobForm[location_not_specified]",
            "value":true
        },
        {
            "siteRule":"/job/employer/job/add",
            "fieldRule":"JobForm[no_of_vacancy]",
            "value":"2"
        },
        {
            "siteRule":"/job/employer/job/add",
            "fieldRule":"JobForm[postal_code]",
            "value":"9684"
        },
        {
            "siteRule":"/job/employer/job/add",
            "fieldRule":"JobForm[requirements]",
            "value":"requirements"
        },
        {
            "siteRule":"/job/employer/job/add",
            "fieldRule":"JobForm[responsibilities]",
            "value":"responsibilities"
        },
        {
            "siteRule":"/job/employer/job/add",
            "fieldRule":"JobForm[salary_negotiable]",
            "value":true
        },
        {
            "siteRule":"/job/employer/job/add",
            "fieldRule":"JobForm[salary]",
            "value":"800"
        },
        {
            "siteRule":"/job/employer/job/add",
            "fieldRule":"JobForm[specific_location]",
            "value":"Ho Chi Minh , Binh Thanh, Dien Bien Phu"
        }
    ]
}